created shopping cart and cart item models and added implementations …
irynamatveieva/book-store pull request #8
Opened 2023-09-04 11:08 UTC by irynamatveieva

…of methods to manage them

2023-09-04 17:59 UTC, aaananas requested changes

2023-09-04 17:59 UTC, aaananas commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @GetMapping()
```suggestion
    @GetMapping
```

2023-09-04 17:59 UTC, aaananas commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```

2023-09-04 17:59 UTC, aaananas commented on src/main/java/com/example/bookstore/mapper/ShoppingCartMapper.java
> +    @Mapping(source = "cartItems", target = "cartItems")
try to keep the same style, in CartItemMapper you used Mappings wrapper annotation

2023-09-04 17:59 UTC, aaananas commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +                && Objects.equals(cartItems, that.cartItems);
```suggestion
        return Objects.equals(id, that.id);
```
it ok to use only id here, related entities might not be initialized

2023-09-05 11:02 UTC, Rommelua requested changes

2023-09-05 11:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +    public boolean equals(Object o) {
We **need** equals/hashCode in CartItem class - we have `HashSet<CartItem>`
And we **do not** need  equals/hashCode in ShoppingCart class

2023-09-05 11:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto addBookToTheShoppingCart(
```suggestion
    @Override
    @Transactional
    public ShoppingCartDto addBookToTheShoppingCart(
```

2023-09-05 11:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.setCartItems(cartItems);
what is it for?

2023-09-05 11:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    public CartItemDto updateCartItem(
@Transactional

2023-09-05 11:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +    @Override
@Transactional

2023-09-05 11:02 UTC, Rommelua commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.setCartItems(cartItems);
```suggestion
        cartItemRepository.delete(cartItem);
```

2023-09-05 12:05 UTC, merged